language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
script:
  - echo $(which g++)
  - echo $(g++ --version)
  - echo $(/usr/bin/g++ --version)
  - make
  - make test
