sudo: required
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
        env:
          - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
before_install:
  - eval "${MATRIX_EVAL}"
  - eval "sudo unlink /usr/bin/gcc && sudo ln -s ${CC} /usr/bin/gcc"
  - eval "sudo unlink /usr/bin/g++ && sudo ln -s ${CXX} /usr/bin/g++"
script: make && make test
