sudo: required
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
        env:
          - GCC_VERSION="5"
before_install:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-${GCC_VERSION} /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-${GCC_VERSION} /usr/bin/g++
script: make && make test
