sudo: required
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      env:
        - GCC_V="4.8"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - GCC_V="5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - GCC_V="8"
before_install:
  - echo $(g++ --version)
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-$GCC_V /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-$GCC_V /usr/bin/g++
  - echo $(g++ --version)
script:
  - tools/install-clang-format.sh 4
  - tools/clang-format-diff.sh
  - make && make test
